### ISSUE TITLE
添加mock项目后，点击启动代理服务器报错

### ISSUE THREAD

**Issue by migismile** [fwon/electron-anyproxy#5]
Uncaught Exception:
Error: listen EADDRINUSE :::8001
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1376:9)
    at /home/mikow/electron-anyproxy-master/proxy.js:145:32
    at /home/mikow/electron-anyproxy-master/node_modules/async/lib/async.js:607:21
    at /home/mikow/electron-anyproxy-master/node_modules/async/lib/async.js:246:17
    at iterate (/home/mikow/electron-anyproxy-master/node_modules/async/lib/async.js:146:13)
    at /home/mikow/electron-anyproxy-master/node_modules/async/lib/async.js:157:25

**Comment by migismile** [comment]
已经解决了.杀掉进程 重新启动就可以了

**Comment by migismile** [comment]
添加mock接口后，开启模拟网速的时候，重启，访问接口 会报Uncaught Exception:
Error: ENOENT: no such file or directory, open '/home/mikow/.anyproxy/cache/cache_r4882/res_body_7'

**Comment by lumixraku** [comment]
> 添加mock接口后，开启模拟网速的时候，重启，访问接口 会报Uncaught Exception:
> Error: ENOENT: no such file or directory, open '/home/mikow/.anyproxy/cache/cache_r4882/res_body_7'

我在拦截修改的时候也有差不多的报错提示  请问这个问题修复了吗
